"""Agent contracts and artifact payloads."""

from pydantic import BaseModel, Field


class AgentDescriptor(BaseModel):
    """Exposed description of a registered specialist agent."""

    key: str
    name: str
    version: str
    purpose: str
    default_model: str | None = None
    allowed_tools: list[str] = Field(default_factory=list)


class ArtifactPayload(BaseModel):
    """Structured artifact generated by an agent or service."""

    title: str
    kind: str
    summary: str | None = None
    sections: list[dict] = Field(default_factory=list)
    metadata: dict = Field(default_factory=dict)


class AgentExecutionInput(BaseModel):
    """Typed payload provided to a specialist agent."""

    session_id: str
    run_id: str
    prompt: str
    context: dict = Field(default_factory=dict)
    constraints: dict = Field(default_factory=dict)
    requested_artifact_kind: str | None = None


class AgentExecutionOutput(BaseModel):
    """Typed response produced by a specialist agent."""

    agent_key: str
    version: str
    artifact: ArtifactPayload
    intermediate_notes: list[str] = Field(default_factory=list)
    citations: list[dict] = Field(default_factory=list)
    next_actions: list[str] = Field(default_factory=list)
    requires_approval: bool = False
    approval_reason: str | None = None
    requested_tools: list[str] = Field(default_factory=list)
