"""Approval workflow persistence."""

from datetime import datetime

from sqlalchemy import Enum, ForeignKey, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin, UUIDPrimaryKeyMixin
from app.models.enums import ApprovalStatus


class ApprovalRequest(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """Approval step generated by orchestration for risky actions."""

    __tablename__ = "approval_requests"

    run_id: Mapped[str] = mapped_column(ForeignKey("agent_runs.id"), index=True, nullable=False)
    checkpoint_id: Mapped[str | None] = mapped_column(
        ForeignKey("agent_checkpoints.id"),
        nullable=True,
    )
    action_type: Mapped[str] = mapped_column(String(100), nullable=False)
    rationale: Mapped[str | None] = mapped_column(Text, nullable=True)
    requested_payload: Mapped[str | None] = mapped_column(Text, nullable=True)
    status: Mapped[ApprovalStatus] = mapped_column(
        Enum(ApprovalStatus, name="approval_status"),
        default=ApprovalStatus.PENDING,
        nullable=False,
        index=True,
    )
    requested_by: Mapped[str] = mapped_column(String(100), default="system")
    decided_by: Mapped[str | None] = mapped_column(String(255), nullable=True)
    decided_at: Mapped[datetime | None] = mapped_column(nullable=True)
    decision_notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    run = relationship("AgentRun", back_populates="approvals")
